apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapp
  minReadySeconds: 50
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 'gcr.io/faizal-gke-cluster/webapp:1.0'
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8090     
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - port: 8090
    targetPort: 8090
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "webapp-static-ip" 
spec:
  # rules:
  # - host: 172.28.128.36
  #   http:
  #   path: /webapp
  backend:
    serviceName: webapp-service
    servicePort: 8090