apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 'dtr.local/demo/webapp:1.0'
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8090     
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    #- protocol: TCP
    - port: 8090
      nodePort: 35000
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: webapp-ingress
#spec:
#  rules:
#  - host: 172.28.128.36
#    http:
#    path: /webapp
#    backend:
#      serviceName: webapp-service
#      servicePort: 8090
